# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Vibe-Ticket

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install --legacy-peer-deps
          # Define CI=false para ignorar warnings de ESLint/TypeScript durante o build
          CI=false npm run build 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # O ARTEFATO é o conteúdo da pasta 'build'
          path: build 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Necessário para o Azure Login
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # O conteúdo do artefato (os arquivos de build) será colocado em uma pasta chamada 'node-app'
          path: node-app 
      
      # Garante que o diretório de trabalho seja a pasta 'node-app' onde o build está.
      - name: Change working directory
        run: cd node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D5A7233630EC49A0B91195EDDAAEB3AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D254560105C646F5B4B4F07EA53BD76C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2CF709E421343BF843663C4FB6FA775 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Vibe-Ticket'
          slot-name: 'Production'
          # CORREÇÃO FINAL: Implanta o conteúdo da pasta 'node-app'
          package: node-app
